FROM openjdk:8-alpine
RUN mkdir -p /opt/crimemap-ui
WORKDIR /opt/crimemap-ui
COPY crimemap-ui/target/crimemap-ui-0.0.1-SNAPSHOT.jar /opt/crimemap-ui
CMD ["java", "-jar", "crimemap-ui-0.0.1-SNAPSHOT.jar"]
