FROM openjdk:8-alpine
RUN mkdir -p /opt/crimemap-backend
WORKDIR /opt/crimemap-backend
COPY crimemap-backend/target/crimemap-backend-0.0.1-SNAPSHOT.jar /opt/crimemap-backend
CMD ["java", "-jar", "crimemap-backend-0.0.1-SNAPSHOT.jar"]
