version: '3.1'

services:

  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hft_2021!
      - POSTGRES_USER=hft
      - POSTGRES_DB=crimemap

  crimemap-backend:
          image: dannybelz/hft-dbsys2-crimemap-backend:v0.1
          ports:
                  - 8090:8090
          depends_on:
                  - postgresdb

  crimemap-webui:
    image: dannybelz/hft-dbsys2-crimemap-webui:v0.1
    ports:
      - 8080:8080
    depends_on:
            - crimemap-backend
