FROM openjdk:8-alpine
RUN mkdir -p /opt/crimemap-webui
WORKDIR /opt/crimemap-webui
COPY crimemap-ui/target/crimemap-webui-0.0.1-SNAPSHOT.jar /opt/crimemap-webui
CMD ["java", "-jar", "crimemap-webui-0.0.1-SNAPSHOT.jar"]
